### ISSUE TITLE
next.js for Vue.js

### ISSUE THREAD

**Issue by egoist** [egoist/vue-requests#1]
eh, honestly I'll wait a bit to see more from [next.js](https://github.com/zeit/next.js), it seems they will have adapters for other frameworks, like `preact` `inferno` et al, I don't know if and how they will support Vue.js

**Comment by atinux** [comment]
Just if people are coming to this issue, there is [Nuxt.js](https://github.com/nuxt/nuxt.js) for something like Next.js for Vue.js.

**Comment by egoist** [comment]
sweet, so I guess I can close this 😀
